### ISSUE TITLE
logo on NavBar items

### ISSUE THREAD

**Issue by parthyadav3105** [parthyadav3105/Turington#4]
Put font **Awesome(fa) logo** with navBar elements

files to edit-
index.html from line 66
navBar.css

![screenshot_2019-01-16 how to create a responsive navigation menu with icons](https://user-images.githubusercontent.com/28928589/51246829-5a83be80-19b1-11e9-8bf0-adab66ed13ee.png)

**Comment by PawanVerma1337** [comment]
Issue Solved

**Comment by parthyadav3105** [comment]
resolved
